### PR TITLE
fix: missing drag scrolling

### LINKED ISSUE #299: Missing drag scrolling support in davi package
**Describe the bug/problem**
The [davi](https://pub.dev/packages/davi) package currently in use to display request params, headers and form data doesn't support drag scrolling (touch) and the package has been dormant for a while.

>**Proposed Solution**
Switch to [data_table_2](https://pub.dev/packages/data_table_2) a more popular and active package and most importantly **supports drag scrolling**.

[repo link - davi](https://github.com/caduandrade/davi_flutter)
[repo link - data_table_2](https://github.com/maxim-saplin/data_table_2)

**Steps to Reproduce the bug/problem**
1. Launch in device with touch input.
2. Attempt to scroll table when params/headers/form data rows overflow available height.

**Expected behavior**
Touch Drag scrolling should work.

**Device Info (The device where you encountered this issue):**
 - OS: Mobile
 - Version: Android 12

### PR DESCRIPTION
**Pull request by DenserMeerkat**
## PR Description

Have used the [data_table_2](https://pub.dev/packages/data_table_2) and matched the current look

davi  | data_table_2 
--- | --- 
current_table | data_table_2

Fixed the text obscuring issue
current  | updated
--- | --- 
current_formData | new_form

## Related Issues

- Related Issue #299,
#250, 
#350 
#33 
- Closes #299,
#250 
#350 
### Checklist
- [X] I have gone through the [contributing guide](https://github.com/foss42/apidash/blob/main/CONTRIBUTING.md)
- [X] I have run the tests (`flutter test`) and all tests are passing

## Added/updated tests?
_We encourage you to add relevant test cases._

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests have not been included_

### CODE REVIEW

File: lib/screens/home_page/editor_pane/details_card/request_pane/request_body.dart
Comment (DenserMeerkat) [inline lib/screens/home_page/editor_pane/details_card/request_pane/request_body.dart:1]: Form data widget required unique EdgeInsets to match table margins of Params and Headers, hence applied padding to individual widgets separately.

File: lib/widgets/form_data_field.dart
Comment (DenserMeerkat) [inline lib/widgets/form_data_field.dart:1]: Had to update content padding since the table's row height has been modified and to match with its corresponding Value Cell Field's padding

File: lib/widgets/headerfield.dart [hunk 1]
```diff
@@ -76,11 +76,16 @@ class _HeaderFieldState extends State<HeaderField> {
         onChanged: widget.onChanged,
         controller: controller,
         focusNode: focusNode,
-        style: kCodeStyle.copyWith(color: colorScheme.onSurface),
+        style: kCodeStyle.copyWith(
+          height: 1.6,
```
Comment (animator) [inline lib/widgets/headerfield.dart:80]: Why are you varying the height?

File: lib/widgets/headerfield.dart [hunk 2]
```diff
@@ -76,11 +76,16 @@ class _HeaderFieldState extends State<HeaderField> {
...
+          color: colorScheme.onSurface,
+        ),
         decoration: InputDecoration(
           hintStyle: kCodeStyle.copyWith(
+              height: 1.6,
```
Comment (animator) [inline lib/widgets/headerfield.dart:85]: Why are you varying the height?

File: lib/widgets/headerfield.dart [hunk 3]
```diff
@@ -76,11 +76,16 @@ class _HeaderFieldState extends State<HeaderField> {
...
               color: colorScheme.outline.withOpacity(kHintOpacity)),
           hintText: widget.hintText,
+          contentPadding: const EdgeInsets.only(bottom: 12),
```
Comment (animator) [inline lib/widgets/headerfield.dart:88]: Why content padding?

**Comment by DenserMeerkat** [comment]
Setting the row height of the table constrained the text fields' heights and caused obscuring of the letters in existing fields.
And by "varying height" if you mean why I have "1.6" at one place and "1.8" at the other its because
the formdatafield has a suffix which affected the alignment.

So adding the height fixed it, but honestly, I don't know if its the right approach.
image

**Comment by animator** [comment]
@DenserMeerkat Actually the suffix inside the textfield in formdata does not make sense. No nesting of widget inside the text field. It should actually be 
<name text field> = <text or file dropdown> <value text field>

**Comment by DenserMeerkat** [comment]
> @DenserMeerkat Actually the suffix inside the textfield in formdata does not make sense. There should not be any nesting of widget inside the text field. It should actually be `<name text field> = <text or file dropdown> <value text field>`
> 
> Please make the necessary modifications.

sure, will change it right away.

**Comment by animator** [comment]
@DenserMeerkat as #313 is merged .. please refactor this PR to account for it.

**Comment by DenserMeerkat** [comment]
> @DenserMeerkat as #313 is merged .. please refactor this PR to account for it.

Yeah, will do it right away.

**Comment by animator** [comment]
@DenserMeerkat sync this PR with the main branch and let me know when it is ready for review.

**Comment by DenserMeerkat** [comment]
Hey @animator 
I've resolved the merge conflicts and the PR is now ready for review.
And I believe #350 also gets resolved with this PR without any code change. Scroll position doesn't get reset on rebuilds.

**Comment by animator** [comment]
@DenserMeerkat Your merge conflict resolution is incorrect.
You have removed the changes that were made in the main branch today.

**Comment by DenserMeerkat** [comment]
Hey @animator 
The PR is now ready for review, and I believe #350 is also solved with this PR without any code change. Scroll position doesn't get reset with rebuilds.

**Comment by DenserMeerkat** [comment]
> @DenserMeerkat Your merge conflict resolution is incorrect. You have removed the changes that were made in the main branch today.

Ohh will look into it now.

**Comment by ashitaprasad** [comment]
You can take a look at this commit where the changes were made -
https://github.com/foss42/apidash/commit/0884a1405835ba3dc98000dfa7bec60b95a9e8b3

**Comment by DenserMeerkat** [comment]
Thanks @ashitaprasad 
I am going through it and replacing with the constants, but I'm not sure what to do about the cell padding changes.

**Comment by DenserMeerkat** [comment]
> You have removed the changes that were made in the main branch today.

I apologize for the overlook, I assumed there were no new changes made in these files in the main branch.

I have added the constant labels, 'Add button' padding changes back, but I'm unsure what to do about  the cell paddings, I believe I have matched the column paddings too.

**Comment by animator** [comment]
I just reviewed the conflict resolution. It looks fine.
Regarding cell padding no changes were made from our end so you can now go ahead and do all testing and give any finishing touches before review.

**Comment by DenserMeerkat** [comment]
The PR is ready for review 👍.
