### PR TITLE
fixed codepane horizontal scroll

### LINKED ISSUE #672: Horizontal scroll not working in CodePane
#### Describe the bug/problem
horizontal scroll isn't working in Code section. there is a scroll bar but it aint working
I think there is something to do with the drawer..
#### Steps to Reproduce the bug/problem
1.Paste any URL
2. Open the Code section
3. try scrolling horizontally

#### Expected behavior
It should scroll horizontally too ..
#### Device Info (The device where you encountered this issue)
 - OS: Android

https://github.com/user-attachments/assets/8b56e9bf-2c44-45d7-9531-233c4df5c1c8

### PR DESCRIPTION
**Pull request by badnikhil**
## PR Description
changed the drawerwidth and modified the codegenpreviewer 
Now the text/singlechildscrollview takes full height of the box ensuring scroll works around the whole box instead of just the text

## Related Issues

- Closes #672 

### Checklist
- [x] I have gone through the [contributing guide](https://github.com/foss42/apidash/blob/main/CONTRIBUTING.md)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I am using the latest Flutter stable branch (run `flutter upgrade` and verify)
- [ ] I have run the tests (`flutter test`) and all tests are passing

## Added/updated tests?
_We encourage you to add relevant test cases._

- [ ] Yes
- [x] No, and this is why: not required

## OS on which you have developed and tested the feature?

- [ ] Windows
- [x] android
- [x] Linux

### CODE REVIEW

File: lib/widgets/previewer_codegen.dart [hunk 1]
```diff
@@ -54,25 +54,28 @@ class _CodeGenPreviewerState extends State<CodeGenPreviewer> {
...
+              thumbVisibility: true,
               controller: controllerH,
-              child: Column(
-                children: [
-                  Row(
-                    children: [
-                      SelectionArea(
+              child: SingleChildScrollView(
+                controller: controllerV,
+                child: IntrinsicHeight(
```
Comment (DenserMeerkat) [inline lib/widgets/previewer_codegen.dart:70]: is the `IntrinsicHeight` widget needed here?

Comment (badnikhil) [reply lib/widgets/previewer_codegen.dart:70]: nope because of constrained box this widget is not necessary here.. Sorry for this oversight .Actaully i was exploring for something which can increase the height of text/singlechildscrollview to its parent box's widget(ignore if i failed to make you understand). i just forget to clean this!

Comment (badnikhil) [reply lib/widgets/previewer_codegen.dart]: Also, the drawerwidth is set to zero. can you confirm if this fits with the intended user experience?

Comment (Udhay-Adithya) [reply lib/widgets/previewer_codegen.dart]: > Also, the drawerwidth is set to zero. can you confirm if this fits with the intended user experience?

I think you can remove the `drawerWidth` property instead of setting it to `0`—by default, it will assign a small value to it (e.g., 20) based on the screen size.

Comment (badnikhil) [reply lib/widgets/previewer_codegen.dart]: > > Also, the drawerwidth is set to zero. can you confirm if this fits with the intended user experience?
> 
> I think you can remove the `drawerWidth` property instead of setting it to `0`—by default, it will assign a small value to it (e.g., 20) based on the screen size.

The scroll experience is not very good... Setting it to 0 is better but limits the drawer...

**Comment by animator** [comment]
Thanks @badnikhil @Udhay-Adithya @DenserMeerkat 
We can finally put this issue to rest 🪦

**Comment by badnikhil** [comment]
> Thanks @badnikhil @Udhay-Adithya @DenserMeerkat We can finally put this issue to rest 🪦

Glad to contribute! will  be dropping a PR for Alamofire-Swift soon .
